name: keepalive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: load service urls from infisical
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: "universal"
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          domain: "https://app.infisical.com"
          project-slug: ${{ vars.INFISICAL_PROJECT_SLUG }}
          env-slug: "qa"
          secret-path: "/service-urls"
          export-type: "env"

      - name: ping services
        run: bash ping.sh
